### ISSUE TITLE
Transparent i18n element?

### ISSUE THREAD

**Issue by alanshaw** [tableflip/i18n-browserify#10]
Sometimes we need to translate something like this:

``` html
<div>
  Some text to be translated followed by <a href="#">a link</a>
</div>
```

What's the best way to translate this? Like this:

``` html
<div>
  <span data-i18n>Some text to be translated followed by</span> <a href="#" data-i18n>a link</a>
</div>
```

If so, it would be good to have an inline i18n element that gets replaced completely by the translated text. e.g.

``` html
<div>
  <i18n>Some text to be translated followed by</i18n> <a href="#" data-i18n>a link</a>
</div>
```

...which becomes:

``` html
<div>
  Some text to be translated followed by <a href="#">a link</a>
</div>
```

**Comment by olizilla** [comment]
This one is tricky. The basic rule of i18n is you can't reliably translate partial sentences, as there are plenty of languages where we'd need to move the position of the text in the `<a>` to somewhere else.

The simple solution may be to allow (some) html in the translation values, a bit like allowing handlebars variables in them, as we do elsewhere.

```
Some text to be translated followed by <a href="#" data-i18n>a link </a>: Wat tekst te vertalen gevolgd door <a href="#" data-i18n> een link </a>
```

I don't love it as a solution, but gluing together partially translated sentences makes for bad i18n.

**Comment by alanshaw** [comment]
I agree, lets leave it as is for now, and I'm not really that keen on the suggestion above. The current implementation will allow for html in the translation string anyway.
